// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	shipment "shipment-service/internal/domain/shipment"
)

// ShipmentRepository is an autogenerated mock type for the ShipmentRepository type
type ShipmentRepository struct {
	mock.Mock
}

type ShipmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipmentRepository) EXPECT() *ShipmentRepository_Expecter {
	return &ShipmentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, s
func (_m *ShipmentRepository) Create(ctx context.Context, s *shipment.Shipment) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *shipment.Shipment) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShipmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ShipmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s *shipment.Shipment
func (_e *ShipmentRepository_Expecter) Create(ctx interface{}, s interface{}) *ShipmentRepository_Create_Call {
	return &ShipmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *ShipmentRepository_Create_Call) Run(run func(ctx context.Context, s *shipment.Shipment)) *ShipmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*shipment.Shipment))
	})
	return _c
}

func (_c *ShipmentRepository_Create_Call) Return(_a0 error) *ShipmentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShipmentRepository_Create_Call) RunAndReturn(run func(context.Context, *shipment.Shipment) error) *ShipmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ShipmentRepository) GetByID(ctx context.Context, id string) (*shipment.Shipment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *shipment.Shipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*shipment.Shipment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *shipment.Shipment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shipment.Shipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShipmentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ShipmentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ShipmentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ShipmentRepository_GetByID_Call {
	return &ShipmentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ShipmentRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *ShipmentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ShipmentRepository_GetByID_Call) Return(_a0 *shipment.Shipment, _a1 error) *ShipmentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShipmentRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*shipment.Shipment, error)) *ShipmentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByReferenceNumber provides a mock function with given fields: ctx, ref
func (_m *ShipmentRepository) GetByReferenceNumber(ctx context.Context, ref string) (*shipment.Shipment, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for GetByReferenceNumber")
	}

	var r0 *shipment.Shipment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*shipment.Shipment, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *shipment.Shipment); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shipment.Shipment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShipmentRepository_GetByReferenceNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByReferenceNumber'
type ShipmentRepository_GetByReferenceNumber_Call struct {
	*mock.Call
}

// GetByReferenceNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *ShipmentRepository_Expecter) GetByReferenceNumber(ctx interface{}, ref interface{}) *ShipmentRepository_GetByReferenceNumber_Call {
	return &ShipmentRepository_GetByReferenceNumber_Call{Call: _e.mock.On("GetByReferenceNumber", ctx, ref)}
}

func (_c *ShipmentRepository_GetByReferenceNumber_Call) Run(run func(ctx context.Context, ref string)) *ShipmentRepository_GetByReferenceNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ShipmentRepository_GetByReferenceNumber_Call) Return(_a0 *shipment.Shipment, _a1 error) *ShipmentRepository_GetByReferenceNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ShipmentRepository_GetByReferenceNumber_Call) RunAndReturn(run func(context.Context, string) (*shipment.Shipment, error)) *ShipmentRepository_GetByReferenceNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewShipmentRepository creates a new instance of ShipmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipmentRepository {
	mock := &ShipmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
