// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	shipment "shipment-service/internal/domain/shipment"
)

// StatusEventRepository is an autogenerated mock type for the StatusEventRepository type
type StatusEventRepository struct {
	mock.Mock
}

type StatusEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *StatusEventRepository) EXPECT() *StatusEventRepository_Expecter {
	return &StatusEventRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, e
func (_m *StatusEventRepository) Create(ctx context.Context, e *shipment.StatusEvent) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *shipment.StatusEvent) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StatusEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type StatusEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - e *shipment.StatusEvent
func (_e *StatusEventRepository_Expecter) Create(ctx interface{}, e interface{}) *StatusEventRepository_Create_Call {
	return &StatusEventRepository_Create_Call{Call: _e.mock.On("Create", ctx, e)}
}

func (_c *StatusEventRepository_Create_Call) Run(run func(ctx context.Context, e *shipment.StatusEvent)) *StatusEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*shipment.StatusEvent))
	})
	return _c
}

func (_c *StatusEventRepository_Create_Call) Return(_a0 error) *StatusEventRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StatusEventRepository_Create_Call) RunAndReturn(run func(context.Context, *shipment.StatusEvent) error) *StatusEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByShipmentID provides a mock function with given fields: ctx, shipmentID
func (_m *StatusEventRepository) GetAllByShipmentID(ctx context.Context, shipmentID string) ([]shipment.StatusEvent, error) {
	ret := _m.Called(ctx, shipmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByShipmentID")
	}

	var r0 []shipment.StatusEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]shipment.StatusEvent, error)); ok {
		return rf(ctx, shipmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []shipment.StatusEvent); ok {
		r0 = rf(ctx, shipmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]shipment.StatusEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shipmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatusEventRepository_GetAllByShipmentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByShipmentID'
type StatusEventRepository_GetAllByShipmentID_Call struct {
	*mock.Call
}

// GetAllByShipmentID is a helper method to define mock.On call
//   - ctx context.Context
//   - shipmentID string
func (_e *StatusEventRepository_Expecter) GetAllByShipmentID(ctx interface{}, shipmentID interface{}) *StatusEventRepository_GetAllByShipmentID_Call {
	return &StatusEventRepository_GetAllByShipmentID_Call{Call: _e.mock.On("GetAllByShipmentID", ctx, shipmentID)}
}

func (_c *StatusEventRepository_GetAllByShipmentID_Call) Run(run func(ctx context.Context, shipmentID string)) *StatusEventRepository_GetAllByShipmentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StatusEventRepository_GetAllByShipmentID_Call) Return(_a0 []shipment.StatusEvent, _a1 error) *StatusEventRepository_GetAllByShipmentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatusEventRepository_GetAllByShipmentID_Call) RunAndReturn(run func(context.Context, string) ([]shipment.StatusEvent, error)) *StatusEventRepository_GetAllByShipmentID_Call {
	_c.Call.Return(run)
	return _c
}

// NewStatusEventRepository creates a new instance of StatusEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatusEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatusEventRepository {
	mock := &StatusEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
